#!/bin/bash
pushd /home/lichao/scratch/pami
popd

#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/single_airplane/car/ /home/lichao/scratch/pami/single_airplane/test_car_res_64.txt /home/lichao/scratch/pami/single_airplane/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_airplane/net2_raw_64.txt /home/lichao/scratch/pami/single_airplane/net2_el_64.txt /home/lichao/scratch/pami/single_airplane/global_summary_64.txt /home/lichao/scratch/pami/single_airplane/voro_centers_64.txt|tee single_airplane_car_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/single_airplane/airplane/ /home/lichao/scratch/pami/single_airplane/test_airplane_res_64.txt /home/lichao/scratch/pami/single_airplane/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_airplane/net2_raw_64.txt /home/lichao/scratch/pami/single_airplane/net2_el_64.txt /home/lichao/scratch/pami/single_airplane/global_summary_64.txt /home/lichao/scratch/pami/single_airplane/voro_centers_64.txt|tee single_airplane_airplane_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/single_airplane/face/ /home/lichao/scratch/pami/single_airplane/test_face_res_64.txt /home/lichao/scratch/pami/single_airplane/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_airplane/net2_raw_64.txt /home/lichao/scratch/pami/single_airplane/net2_el_64.txt /home/lichao/scratch/pami/single_airplane/global_summary_64.txt /home/lichao/scratch/pami/single_airplane/voro_centers_64.txt|tee single_airplane_face_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/single_airplane/motorbike/ /home/lichao/scratch/pami/single_airplane/test_motorbike_res_64.txt /home/lichao/scratch/pami/single_airplane/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_airplane/net2_raw_64.txt /home/lichao/scratch/pami/single_airplane/net2_el_64.txt /home/lichao/scratch/pami/single_airplane/global_summary_64.txt /home/lichao/scratch/pami/single_airplane/voro_centers_64.txt|tee single_airplane_motorbike_64.txt

ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/single_car/car/ /home/lichao/scratch/pami/single_car/test_car_res_64.txt /home/lichao/scratch/pami/single_car/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_car/net2_raw_64.txt /home/lichao/scratch/pami/single_car/net2_el_64.txt /home/lichao/scratch/pami/single_car/global_summary_64.txt /home/lichao/scratch/pami/single_car/voro_centers_64.txt|tee single_car_car_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/single_car/airplane/ /home/lichao/scratch/pami/single_car/test_airplane_res_64.txt /home/lichao/scratch/pami/single_car/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_car/net2_raw_64.txt /home/lichao/scratch/pami/single_car/net2_el_64.txt /home/lichao/scratch/pami/single_car/global_summary_64.txt /home/lichao/scratch/pami/single_car/voro_centers_64.txt|tee single_car_airplane_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/single_car/face/ /home/lichao/scratch/pami/single_car/test_face_res_64.txt /home/lichao/scratch/pami/single_car/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_car/net2_raw_64.txt /home/lichao/scratch/pami/single_car/net2_el_64.txt /home/lichao/scratch/pami/single_car/global_summary_64.txt /home/lichao/scratch/pami/single_car/voro_centers_64.txt|tee single_car_face_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/single_car/motorbike/ /home/lichao/scratch/pami/single_car/test_motorbike_res_64.txt /home/lichao/scratch/pami/single_car/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_car/net2_raw_64.txt /home/lichao/scratch/pami/single_car/net2_el_64.txt /home/lichao/scratch/pami/single_car/global_summary_64.txt /home/lichao/scratch/pami/single_car/voro_centers_64.txt|tee single_car_motorbike_64.txt
#
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/single_face/car/ /home/lichao/scratch/pami/single_face/test_car_res_64.txt /home/lichao/scratch/pami/single_face/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_face/net2_raw_64.txt /home/lichao/scratch/pami/single_face/net2_el_64.txt /home/lichao/scratch/pami/single_face/global_summary_64.txt /home/lichao/scratch/pami/single_face/voro_centers_64.txt|tee single_face_car_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/single_face/airplane/ /home/lichao/scratch/pami/single_face/test_airplane_res_64.txt /home/lichao/scratch/pami/single_face/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_face/net2_raw_64.txt /home/lichao/scratch/pami/single_face/net2_el_64.txt /home/lichao/scratch/pami/single_face/global_summary_64.txt /home/lichao/scratch/pami/single_face/voro_centers_64.txt|tee single_face_airplane_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/single_face/face/ /home/lichao/scratch/pami/single_face/test_face_res_64.txt /home/lichao/scratch/pami/single_face/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_face/net2_raw_64.txt /home/lichao/scratch/pami/single_face/net2_el_64.txt /home/lichao/scratch/pami/single_face/global_summary_64.txt /home/lichao/scratch/pami/single_face/voro_centers_64.txt|tee single_face_face_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/single_face/motorbike/ /home/lichao/scratch/pami/single_face/test_motorbike_res_64.txt /home/lichao/scratch/pami/single_face/kmeans_800_64.txt nil /home/lichao/scratch/pami/single_face/net2_raw_64.txt /home/lichao/scratch/pami/single_face/net2_el_64.txt /home/lichao/scratch/pami/single_face/global_summary_64.txt /home/lichao/scratch/pami/single_face/voro_centers_64.txt|tee single_face_motorbike_64.txt
